### ISSUE TITLE
words not found

### ISSUE THREAD

**Issue by HugoFlorentino** [lucabol/Zig-Forth#1]
I cloned the repo, and built the project on Windows with Zig 0.9.1, so far so good

However during execution, when I tried entering words declared in the `Vm` struct (with and without the `_op` prefix), they don't seem to work. Only `op_notFound` executes, regardless of what I enter.

I must admit I am not familiar with Forth though, so perhaps I am missing a step.

Very cool and elegant project though.

**Comment by lucabol** [comment]
Hack, forgot to say, it doesn't work in Windows :-) There is a compiler bug that I have logged for that. Sorry :-) If you try it in wsl, it should work.

**Comment by lucabol** [comment]
https://github.com/ziglang/zig/issues/11035
